#!/bin/bash

# Halt if virtualenv is not installed
if [ ! -x $(which virtualenv) ]; then 
    echo -e "! Check if virtualenv is installed";
    exit 1
fi

# Create a nice virtual environment
virtualenv .

# Install pip
if [ ! -x $(which pip) ]; then 
    easy_install pip
fi

# Initialize environment and install required modules
source ./bin/activate
pip install -r requirements.txt

cat << LIBRARY_MESSAGE

If you had any errors about lxml, do this on Ubuntu:

  sudo apt-get install libxml2-dev libxslt-dev

And this on an RHEL-based box:

  sudo yum install libxml2-devel libxslt-devel

LIBRARY_MESSAGE
